#!/bin/bash

# Submits 10 jobs, which each say Hello World and count to their respective job number
 
executable = 02hello_count.sh
universe = vanilla
Error  = logs/02hello_count.$(Process).err
Output = logs/02hello_count.$(Process).out
Log    = logs/02hello_count.$(Process).log

request_cpus = 1
request_memory = 1000MB
request_disk = 100MB
+WANT_RCC_ciconnect = True
+ProjectName = "xenon1t"
+AccountingGroup = "group_opportunistic.xenon1t.processing"
arguments = $(Process)

queue 10
